### ISSUE TITLE
Winium Desktop Xpath Issue

### ISSUE THREAD

**Issue by rehananon** [2gis/Winium#42]
While locating an element like Textbox by using Xpath i'm getting several errors everytime. I just want to locate a textbox with xpath because there are already two textbox with same classname and no automation id, But while I'm trying to access that particular element with Xpath getting error like"Native" and other kinds of error. I have used- //*[@ClassName='textbox'] and also /*[@ClassName='textbox'] and   
//*[contains(@ClassName,'textbox')], None of them worked for me.

Please Reply @ my email address asap coz I need this for my Project Deliverables.

**Comment by NickAb** [comment]
Could you please provide more information:

1. Do you use lowercase `textbox` or correctly cased `TextBox`?
2. Do you search for element starting from another element in your UI, i.e. `parent.find_element_by_xpath(...)` vs `driver.find_element_by_xpath(...)`?
3. What errors do you get? Please provide stacktrace.

**Comment by rehananon** [comment]
I have written TextBox and used driver.findelementbyxpath.

I cant recall the Exact Stack Trace Information But I was getting was some
"Native" error.


My requirement is to send keys to an textbox element, that element doesnot
have any id or name, has only one classname but that is not unique I mean
there are multiple textbox in the same window having the same classname.

Please followup as I work in an MNC company and I need to submit a
automation script to the client within 15th of this month.

**Comment by NickAb** [comment]
Calling XPath for TextBox from driver might be the problem. In Winium.Desktop `driver` represents whole desktop, not only your app under a test. You have to limit search scope.
Please use following patter
```py
aut=driver.find_element_by_xpath("/*[@AutomationId='AutMainWindow']
aut.find_element_by_xpath("//*[@ClassName='TextBox']")
```

Note that we first locale main windows of our application, in this example it has AutomationId = 'AutMainWindow', in your case it might not have AutomationId, but it should have unique window name at least.
Locate all other elements starting from `aut` (your app only), not the `driver` (whole desktop and open windows in your system).

**Comment by rehananon** [comment]
And I'm using java!

**Comment by rehananon** [comment]
Ok Thank You Nick. I will try what u said. Can u please write me@
mintumukherjeedsms@gmail.com so that I can mail you directly when I will
need.

**Comment by rehananon** [comment]
Hope this will work! Thanks Nick for following up. I will let u know on Monday.

**Comment by NickAb** [comment]
You can find our contact info in readme for Dekstop https://github.com/2gis/Winium.Desktop#contact and Mobile https://github.com/2gis/Winium.Mobile#contact

**Comment by rehananon** [comment]
WebElement el= driver.findElement(By.xpath("/*[@Name='XYZ'])"));

el.findElement(By.className("TextBox")).sendKeys("hello");


Error INFO:-

Exception in thread "main" org.openqa.selenium.WebDriverException: '/*[@Name='XYZ'])' has an invalid token. (WARNING: The server did not provide any stacktrace information)

 Element info: {Using=xpath, value=/*[@Name='XYZ'])}
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
	at java.lang.reflect.Constructor.newInstance(Unknown Source)

**Comment by rehananon** [comment]
Done! Working as Expected..
Thanks alot..

**Comment by 5ach1n** [comment]
Can I use RuntimeId for locating elements? Because Automation Id is same for all the textbox in my application

**Comment by jsingh-qualitrol** [comment]
@rehananon 
How did you solve the issue to locate element in desktop application by Winium.
I am unable to locate the element 
Pls help...

**Comment by ravindrakolhe** [comment]
Hi, I am using below xpath......still getting an issue. Please help me

driver.findElementByXPath("//*[contains(@Class,'TkChild') and contains(@Instance,'8')]").click();

Error:-
*** Element info: {Using=xpath, value=//*[contains(@Class,'TkChild') and contains(@Instance,'8')]}
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)

**Comment by ghost** [comment]
I am not able to find out the xpath for windows application

**Comment by rehananon** [comment]
Use any desktop inspector. And then try to form a xpath! Sorry for late
reply I was not able to accss my mailbox for long time
